#%RAML 1.0
title: sys-error-log


/getLogs: # optional resource
  get: # HTTP method declaration
    responses: # declare a response
      200: # HTTP status code
        body: # declare content of response
          application/json: # media type
           
            example: | # example of how a response looks
              {
                 "servicename": "Error log service",
                "source": "string ",
                "target": "string ",
                "errormsg": "string",
                "payload": "string",
                "errortime": "2022-11-20 03:48:23"
              }